package com.mycompany.internshipsystemy2s3.entity;

public enum Skill {
    DEVOPS, FRONTEND, BACKEND, FULLSTACK, MOBILE, DATA_SCIENTIST, MACHINE_LEARNING_ENGINEER, 
    CLOUD_ENGINEER, SECURITY_ENGINEER, DATABASE_ADMINISTRATOR
}